
language: node_js

node_js:
- lts/*

notifications:
  email: false

before_install:
- npm install --global nyc mocha typescript rimraf

install:
- npm install

script:
- npm run clean
- npm run build
- npm run build-docs
- npm run tslint
- npm run coveralls

branches:
  only:
  - master
