
language: node_js

node_js:
- lts/*

notifications:
  email: false

before_install:
- npm install --global nyc mocha typescript

install:
- npm run update-versions

script:
- npm run build
- npm run test
- npm run tslint

branches:
  only:
  - master

