
language: node_js

node_js:
- lts/*

notifications:
  email: false

before_install:
- npm install --global nyc mocha typescript

install:
- npm run update-versions

script:
- npm run clean
- npm run build
- npm run build-docs
- npm run tslit
- npm run coveralls


branches:
  only:
  - master

