language: node_js

node_js:
- lts/*

notifications:
  email: false

before_install:
- npm install --global nyc mocha typescript shx
  
install:
- npm install

before_script:
#- npm run build

script:
#- npm run build-docs
#- npm run coveralls

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
  - /^v\d+\.\d+\.\d+$/

after_success:
- npm run travis-deploy-once "npm run semantic-release"
#- npm run typedoc
- npm pack

deploy:

  - provider: pages
    skip_cleanup: true
    local_dir: docs/reference
    github_token: $GITHUB_TOKEN
    on:
      tags: false
  
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "BotServer-*.tgz"
    skip_cleanup: true
    on:
      tags: false
      branch: master

  - provider: npm
    skip_cleanup: true
    email: "operations@pragmatismo.io"
    api_key: $NPM_TOKEN
    on:
      tags: false
      branch: master
